// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MicwayTech.Data;

namespace MicwayTech.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190129064523_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MicwayTech.Domain.Driver", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("DOB")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("isDeleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("lastName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("DriverDetails");

                    b.HasData(
                        new { Id = "1125e958-4f21-4f2f-98ad-de681a5d7c5b", DOB = new DateTime(1900, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "John.Mack@micway.com", FirstName = "John", IsDeleted = false, LastName = "Mack" },
                        new { Id = "d4f225a1-69f3-4e9a-a626-7dcb33dbc625", DOB = new DateTime(1928, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "Hubert.DAF@micway.com", FirstName = "Hubert", IsDeleted = false, LastName = "DAF" },
                        new { Id = "3a00db3b-6689-4d4b-9db7-a1d6f641368e", DOB = new DateTime(1900, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "George.Kenworth@micway.com", FirstName = "George", IsDeleted = false, LastName = "Kenworth" },
                        new { Id = "09d4965b-b004-4058-a083-37e72c53dae0", DOB = new DateTime(1900, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "Benjamin.Caterpillar@micway.com", FirstName = "Benjamin", IsDeleted = false, LastName = "Caterpillar" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
